#!/usr/bin/env node

import { execFileSync } from 'node:child_process';
import {
  cpSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  checkRuntimeProjection,
  compareRuntimeProjections,
  generateRuntimeProjection,
} from './build-runtime-js.ts';

const SCRIPT_PATH = fileURLToPath(import.meta.url);
const REPO_ROOT = resolve(dirname(SCRIPT_PATH), '..');
const JAVASCRIPT_EXTENSION = /\.(?:[cm]?js|jsx)$/u;

function expect(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function trackedJavaScriptPaths(root: string): string[] {
  return execFileSync('git', ['-C', root, 'ls-files', '-z'], {
    encoding: 'utf8',
    maxBuffer: 16 * 1024 * 1024,
  })
    .split('\0')
    .filter((path) => JAVASCRIPT_EXTENSION.test(path));
}

function main(): void {
  const tempRoot = mkdtempSync(join(tmpdir(), 'aleph-runtime-js-tests-'));
  const cases: Array<{ name: string; status: 'PASS' | 'FAIL'; error?: string }> = [];
  const run = (name: string, action: () => void): void => {
    try {
      action();
      cases.push({ name, status: 'PASS' });
    } catch (error) {
      cases.push({
        name,
        status: 'FAIL',
        error: error instanceof Error ? error.message : String(error),
      });
    }
  };
  try {
    run('tracked JavaScript is generated TypeScript emit', () => {
      const trackedJavaScript = trackedJavaScriptPaths(REPO_ROOT);
      expect(trackedJavaScript.length > 0, 'tracked runtime projection is empty');
      const outsideProjection = trackedJavaScript.filter(
        (path) => !path.startsWith('runtime-js/'),
      );
      expect(
        outsideProjection.length === 0,
        `authored JavaScript is forbidden: ${outsideProjection.join(', ')}`,
      );

      const attributes = execFileSync(
        'git',
        [
          '-C',
          REPO_ROOT,
          'check-attr',
          'linguist-generated',
          '--',
          ...trackedJavaScript,
        ],
        { encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 },
      ).trimEnd().split('\n');
      const unclassified = attributes.filter(
        (line) => !line.endsWith(': linguist-generated: true'),
      );
      expect(
        attributes.length === trackedJavaScript.length && unclassified.length === 0,
        `tracked JavaScript is not classified as generated: ${unclassified.join(', ')}`,
      );

      const report = checkRuntimeProjection(REPO_ROOT);
      expect(report.result === 'PASS', report.errors.join('; '));
      expect(report.files > 0, 'runtime projection is empty');
    });

    const first = join(tempRoot, 'first');
    const second = join(tempRoot, 'second');
    generateRuntimeProjection(REPO_ROOT, first);
    generateRuntimeProjection(REPO_ROOT, second);

    run('repeated projection emit is byte-identical', () => {
      const report = compareRuntimeProjections(first, second);
      expect(report.result === 'PASS', report.errors.join('; '));
    });

    run('tampered generated byte fails closed', () => {
      const tampered = join(tempRoot, 'tampered');
      cpSync(first, tampered, { recursive: true });
      const launcher = join(tampered, 'adapters', 'loa', 'src', 'launcher.js');
      writeFileSync(launcher, Buffer.concat([readFileSync(launcher), Buffer.from('\n// drift\n')]));
      const report = compareRuntimeProjections(first, tampered);
      expect(report.result === 'FAIL', 'tampered runtime projection passed');
      expect(report.errors.some((error) => error.includes('launcher.js')),
        `tamper diagnostic omitted launcher: ${report.errors.join('; ')}`);
    });

    run('extra generated file fails closed', () => {
      const extra = join(tempRoot, 'extra');
      cpSync(first, extra, { recursive: true });
      writeFileSync(join(extra, 'extra.js'), 'export {};\n');
      const report = compareRuntimeProjections(first, extra);
      expect(report.result === 'FAIL', 'extra runtime file passed');
      expect(report.errors.some((error) => error.includes('extra.js')),
        `extra-file diagnostic omitted path: ${report.errors.join('; ')}`);
    });

    run('runtime imports contain no TypeScript extension', () => {
      const text = readFileSync(
        join(first, 'adapters', 'loa', 'src', 'cli.js'),
        'utf8',
      );
      expect(!/from\s+['"][^'"]+\.ts['"]|import\(['"][^'"]+\.ts['"]\)/u.test(text),
        'compiled CLI retains a TypeScript runtime import');
    });
  } finally {
    rmSync(tempRoot, { recursive: true, force: true });
  }
  for (const item of cases) {
    console.log(`${item.status} ${item.name}${item.error ? `: ${item.error}` : ''}`);
  }
  const passed = cases.filter((item) => item.status === 'PASS').length;
  const result = passed === cases.length ? 'PASS' : 'FAIL';
  console.log(`RESULT: ${result} (${passed}/${cases.length})`);
  process.exitCode = result === 'PASS' ? 0 : 1;
}

if (resolve(process.argv[1] || '') === SCRIPT_PATH) main();
